### ISSUE TITLE
webpack server init error

### ISSUE THREAD

**Issue by Fedreg** [eggplanetio/vue-map-dragger#4]
After setting up dependencies per video 2 I get an error when running npm run dev.  I've tried with 0.0.0.0. ip, actual ip, and changed the default port number.  Running Ubuntu 14.04 remote

Thanks for any help
![image](https://cloud.githubusercontent.com/assets/17401067/18470235/449e8038-7971-11e6-88fd-93f48b06983a.png)

**Comment by briangonzalez** [comment]
@Fedreg Have you run `npm install`?

**Comment by Fedreg** [comment]
yes and everything appears to be installed correctly.  I'll try reinstalling everything again and see if it works?  i uninstalled another server that was also broadcasting to port 8080.  Maybe this was interfering....not very experienced with webpack.   Thanks for the vids!

**Comment by briangonzalez** [comment]
Can you please run?

```
ls -la
```

then:

```
la -la node_modules
```

**Comment by briangonzalez** [comment]
(from within your project's root)

**Comment by Fedreg** [comment]
![image](https://cloud.githubusercontent.com/assets/17401067/18475652/e8c42e2c-798c-11e6-8093-cac6e277a8d8.png)

**Comment by briangonzalez** [comment]
You should have a lot more than that. See my truncated `ls -la` below:

```
code/eggplanet/vue-map-dragger on master via ⬢ v6.5.0
❯ ls -la node_modules
total 0
drwxr-xr-x  472 bgonzalez  staff  16048 Sep 10 18:01 .
drwxr-xr-x   13 bgonzalez  staff    442 Sep 12 07:44 ..
drwxr-xr-x   34 bgonzalez  staff   1156 Sep 10 09:39 .bin
drwxr-xr-x   11 bgonzalez  staff    374 Sep 10 09:38 Base64
drwxr-xr-x    6 bgonzalez  staff    204 Sep 10 09:38 abbrev
drwxr-xr-x    7 bgonzalez  staff    238 Sep 10 09:38 accepts
drwxr-xr-x   16 bgonzalez  staff    544 Sep 10 09:39 acorn
drwxr-xr-x    6 bgonzalez  staff    204 Sep 10 09:38 align-text
drwxr-xr-x    6 bgonzalez  staff    204 Sep 10 09:38 alphanum-sort
drwxr-xr-x    7 bgonzalez  staff    238 Sep 10 09:38 amdefine
drwxr-xr-x    6 bgonzalez  staff    204 Sep 10 09:38 ansi-regex
drwxr-xr-x    6 bgonzalez  staff    204 Sep 10 09:38 ansi-styles
drwxr-xr-x    6 bgonzalez  staff    204 Sep 10 09:38 anymatch
drwxr-xr-x    8 bgonzalez  staff    272 Sep 10 09:39 argparse
drwxr-xr-x    6 bgonzalez  staff    204 Sep 10 09:38 arr-diff
drwxr-xr-x    6 bgonzalez  staff    204 Sep 10 09:38 arr-flatten
drwxr-xr-x    6 bgonzalez  staff    204 Sep 10 09:38 array-flatten
drwxr-xr-x    6 bgonzalez  staff    204 Sep 10 09:38 array-unique
drwxr-xr-x    6 bgonzalez  staff    204 Sep 10 09:38 arrify
drwxr-xr-x    8 bgonzalez  staff    272 Sep 10 09:39 asn1.js
drwxr-xr-x   10 bgonzalez  staff    340 Sep 10 09:38 assert
.......
drwxr-xr-x    6 bgonzalez  staff    204 Sep 10 09:38 window-size
drwxr-xr-x    8 bgonzalez  staff    272 Sep 10 09:38 wordwrap
drwxr-xr-x    6 bgonzalez  staff    204 Sep 10 09:38 wrap-ansi
drwxr-xr-x    6 bgonzalez  staff    204 Sep 10 09:38 y18n
drwxr-xr-x   10 bgonzalez  staff    340 Sep 10 09:38 yallist
drwxr-xr-x   12 bgonzalez  staff    408 Sep 10 09:39 yargs
drwxr-xr-x    9 bgonzalez  staff    306 Sep 10 09:39 yargs-parser

code/eggplanet/vue-map-dragger on master via ⬢ v6.5.0
```

Would you mind running?

```
rm -rf node_modules && npm i 
npm run dev
```

**Comment by Fedreg** [comment]
process killed.  ran three times.   Should i just start over?  thanks for the help

**Comment by briangonzalez** [comment]
I am confused – what do you mean?

**Comment by Fedreg** [comment]
npm gets hung up and returns "killed".  No error, just "killed"

**Comment by briangonzalez** [comment]
> npm gets hung up and returns "killed"

which command gets killed?

**Comment by Fedreg** [comment]
rm -rf node_modules && npm i

**Comment by briangonzalez** [comment]
You're likely running into RAM issues. I've seen this before.

https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-12-04

**Comment by Fedreg** [comment]
ok, this is a small test server.  only 512mb of RAM but nothing else on it.   i'll upgrade it or try on another machine to see what happens.  thanks again

**Comment by briangonzalez** [comment]
Increasing the swap will also help. Cheers.

**Comment by Fedreg** [comment]
doubled ram, removed node modules, and reran npm i.  Now working as expected.  thanks again!
